language: perl
os:
  - linux
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'drop   database travis;' -U postgres || true
  - psql -c 'create database travis;' -U postgres
test:
  adapter: postgresql
  database: travis
  username: postgres
env:
  - AUTOMATED_TESTING=1
install:
  - cpanm --quiet Time::HiRes DBI
  - cpanm --quiet DBD::SQLite || true
  - cpanm --quiet DBD::CSV    || true
  - cpanm --quiet DBD::Pg     || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
