language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
env:
  - AUTOMATED_TESTING=1
install:
  - cpanm --quiet Time::HiRes DBI DBD::SQLite DBD::CSV DBD::Pg
