language: perl
os:
  - linux
dist: trusty
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
services:
  - postgresql
before_script:
  - psql -c 'drop   database travis;' -U postgres || true
  - psql -c 'create database travis;' -U postgres
test:
  adapter: postgresql
  database: travis
  username: postgres
env:
  - AUTOMATED_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
  - cpanm --quiet Time::HiRes DBI
  - cpanm --quiet DBD::SQLite || true
  - cpanm --quiet DBD::CSV    || true
  - cpanm --quiet DBD::Pg     || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
